### ISSUE TITLE
Broderbund News Magazine

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4656]
I believe, it's a full set, regardless of starting from the "vol. 2". Broderbund was created this very year.

- [ ] Broderbund News - vol.2 #4 - Fall 1986.pdf
- [ ] Broderbund News - vol.3 #1 - Winter 1987.pdf
- [ ] Broderbund News - vol.3 #2 - Spring 1987.pdf
- [ ] Broderbund News - vol.3 #3 - Summer 1987.pdf
- [ ] Broderbund News - vol.3 #4 - Fall 1987.pdf
- [ ] Broderbund News - vol.4 #1 - Winter-Spring 1988.pdf
- [ ] Broderbund News - vol.4 #2 - Summer 1988.pdf

**Comment by exoscoriae** [comment]
I located several missing issues. Vol 2 issues1, 2 and 3. And vol 1 issue 1, which appears to have been the only release that year.

That appears to be a complete set?
