### ISSUE TITLE
Westwood Studios News & Notes

### ISSUE THREAD

**Issue by SmilingSpectre** [exoscoriae/eXoDOS#4658]
6 issues from 7, I believe. There are 8 and 9 exists, but they are online-only, as HTML, so I didn't download them

- [ ] Westwood Studios News & Notes - vol. 1 #1 - Summer 1992.pdf
- [ ] Westwood Studios News & Notes - vol. 1 #2 - Fall 1992.pdf
- [ ] Westwood Studios News & Notes - vol. 1 #3 - Winter-Spring 1993.pdf
- [ ] Westwood Studios News & Notes - vol. 1 #4 - Summer 1993.pdf
- [ ] Westwood Studios News & Notes - vol. 1 #5 - Fall 1993.pdf
- [ ] Westwood Studios News & Notes #7.pdf

Sorry, I will not rename # only because Github doesn't like it.

**Comment by exoscoriae** [comment]
added to magazines
